export const PROFILE_PATH = '/perfil'
export const CATEGORIES_PATH = '/categorias'
export const CONTACT_PATH = '/contacto'
export const LOGIN_PATH = '/login'
export const PRODUCT_PATH = '/producto'
export const BLOG_PATH = '/blog'
export const STORES_PATH = '/tiendas'
